apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone-container
        image: pouellette123/capstone
        ports:
        - containerPort: 8079
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: NodePort
  selector:
    app: capstone
  ports:
  - protocol: TCP
    port: 8079
    targetPort: 8079
    nodePort: 32001
